version: "3"

services:

  unbound:
    image: r.cfcr.io/maltore/maltore/homelabdns:master
    ports:
      - "53:53/udp"
      - "54:54"
    deploy:
      placement:
        constraints: [node.role == manager]
